name: Genrate ASCII Art
on: [push]

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay cmd
              run: cowsay -f dragon "Beware! The dragon has awoken!" >> dragon.txt

            - name: upload dragon text file 
              uses: actions/upload-artifact@v3
              with:
                  name: dragon-artifact
                  path: dragon.txt
        
    build_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: download dragon text file 
              uses: actions/download-artifact@v3
              with:
                name: dragon-artifact

            - name: test file exists
              run: grep -i "dragon" dragon.txt

  
    build_job_3:
        runs-on: ubuntu-latest
        needs: build_job_2
        steps:
            - name: download dragon text file 
              uses: actions/download-artifact@v3
              with:
                name: dragon-artifact

            - name: read file details
              run: cat dragon.txt && ls -ltra