name: Genrate ASCII Art
on: [push]

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay cmd
              run: cowsay -f dragon "Beware! The dragon has awoken!" >> dragon.txt

            - name: sleep for 30 seconds
              run: sleep 30
        
    build_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: sleep for 10 seconds
              run: sleep 10

            - name: test file exists
              run: grep -i "dragon" dragon.txt

  
    build_job_3:
        runs-on: ubuntu-latest
        needs: build_job_2
        steps:
            - name: display file content
              run: cat dragon.txt

            - name: read file details
              run: cat dragon.txt && ls -ltra